---

x-common: &common
  build:
    target: development
    context: .
    dockerfile: Dockerfile-dev
    args:
      - PYTHON_VERSION=${PYTHON_VERSION:-3.11}
  image: "difflume:dev"
#  env_file: .env
  volumes:
    - .:/opt/code

services:
  devtools:
    <<: *common
    command: sleep infinity

  app:
    <<: *common
    restart: "no"
